#! /bin/bash

set -x

PAC=fk-cs-language-service
USER=fk-cs-language-service
GROUP=fk-erp

USER_ID=35010
GID=4010

JMX_PORT=6902

if [ "$1" == "configure" ] ; then


    #creating user if it doesnt exist
    if ! getent group $GROUP > /dev/null; then
        groupadd -g $GID $GROUP
    fi

    if ! getent passwd $USER_ID > /dev/null; then
        adduser --system --uid $USER_ID --home /usr/share/$PAC --no-create-home \
        --ingroup $GROUP --disabled-password --shell /bin/false \
        $USER
    fi

    if [ "$PAC" ]; then
      LOG_DIR="/var/log/flipkart/erp/${PAC}"
      [ -d "$LOG_DIR" ] || mkdir -p $LOG_DIR
      chown -R $USER:$GROUP /usr/share/$PAC
      #chown -R $USER:$GROUP /etc/$PAC
      [ -d "$LOG_DIR" ] && chown -R $USER:$GROUP $LOG_DIR && chmod 777 $LOG_DIR
    fi

    SERVICE_NAME=$PAC
    /usr/share/fk-ops-servicebuilder/servicebuilder.pl -N $SERVICE_NAME  -R /usr/share/$PAC/service/run.sh || exit 1
    chmod 755 /etc/sv/$SERVICE_NAME/run

    echo "STOPPING THE SERVICE"
    sudo svc -d /etc/sv/$SERVICE_NAME

   sudo svc -t /etc/sv/fk-crm-app-connections

    echo "STARTING THE SERVICE"
    sudo svc -u /etc/sv/$SERVICE_NAME

     sudo /etc/init.d/rsyslog restart

    echo "Adding jmx values :"

    /usr/share/$PAC/service/create-cosmos-jmx-file $JMX_PORT

    echo "ALL DONE....."


fi
exit 0
